DROP ALL OBJECTS;
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE items(
    id bigint generated by default as identity not null,
    name varchar not null,
    description varchar not null,
    available varchar not null,
    owner bigint references USERS(id) on delete cascade,
    request bigint
);